name: 🚀 Feature
description: Something missing ?
title: "[FEATURE]"
labels: 
  - enhancement
projects: 
  - "AndreasLrx/4"
body:
- type: textarea
  attributes:
    label: Describe the feature Behavior
    description: |
      A concise description of what you're expecting.
      If you don't have a clear idea, you can describe the problem you are facing and we will try to find a solution together.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the needs
    description: |
      Why you need this feature or think it will be usefull to the library.
      Do not hesistate to include some examples or pseudo code snippets.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
